project:
  type: website

website:
  title: "Homepage"
  navbar:
    left:
      - text: Blogposts
        href: blog-posts/index.qmd
    right:
      - icon: github
        href: https://github.com/DeenaLad
      - icon: linkedin
        href: https://www.linkedin.com/in/deena-lad-307645214/

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full
    fig-align: center
